# GitHub Repository Metadata
# Apply via: gh repo edit syncupsuite/webplatform4sync [flags]
# Or manually in GitHub Settings > General

description: "Platform standards, skills, and scaffold templates for SyncUpSuite multi-tenant SaaS projects"

topics:
  - claude-code-skills
  - multi-tenant
  - saas-platform
  - cloudflare-workers
  - neon-postgres
  - design-tokens
  - row-level-security
  - better-auth
  - scaffold-templates
  - edge-computing
  - dtcg-tokens
  - drizzle-orm
  - react
  - typescript
  - tailwind-css

homepage: ""

# Visibility: public

features:
  wiki: false
  issues: true
  projects: false
  discussions: false

# Branch protection
default_branch: main
